export const GET_CATEGORIES_REQUEST = 'meraki/Category/GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'meraki/Category/GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'meraki/Category/GET_CATEGORIES_ERROR';